export const CREATE_ANNOUNCEMENT_REQUEST = "CREATE_ANNOUNCEMENT_REQUEST";
export const CREATE_ANNOUNCEMENT_SUCCESS = "CREATE_ANNOUNCEMENT_SUCCESS";
export const CREATE_ANNOUNCEMENT_FAIL = "CREATE_ANNOUNCEMENT_FAIL";

export const MY_ANNOUNCEMENTS_REQUEST = "MY_ANNOUNCEMENTS_REQUEST";
export const MY_ANNOUNCEMENTS_SUCCESS = "MY_ANNOUNCEMENTS_SUCCESS";
export const MY_ANNOUNCEMENTS_FAIL = "MY_ANNOUNCEMENTS_FAIL";

export const NEW_ANNOUNCEMENT_REQUEST = "NEW_ANNOUNCEMENT_REQUEST";
export const NEW_ANNOUNCEMENT_SUCCESS = "NEW_ANNOUNCEMENT_SUCCESS";
export const NEW_ANNOUNCEMENT_RESET = "NEW_ANNOUNCEMENT_RESET";
export const NEW_ANNOUNCEMENT_FAIL = "NEW_ANNOUNCEMENT_FAIL";

export const ANNOUNCEMENT_DETAILS_REQUEST = "ANNOUNCEMENT_DETAILS_REQUEST";
export const ANNOUNCEMENT_DETAILS_SUCCESS = "ANNOUNCEMENT_DETAILS_SUCCESS";
export const ANNOUNCEMENT_DETAILS_FAIL = "ANNOUNCEMENT_DETAILS_FAIL";

export const ALL_ANNOUNCEMENTS_REQUEST = "ALL_ANNOUNCEMENTS_REQUEST";
export const ALL_ANNOUNCEMENTS_SUCCESS = "ALL_ANNOUNCEMENTS_SUCCESS";
export const ALL_ANNOUNCEMENTS_FAIL = "ALL_ANNOUNCEMENTS_FAIL";

export const UPDATE_ANNOUNCEMENT_REQUEST = "UPDATE_ANNOUNCEMENT_REQUEST";
export const UPDATE_ANNOUNCEMENT_SUCCESS = "UPDATE_ANNOUNCEMENT_SUCCESS";
export const UPDATE_ANNOUNCEMENT_FAIL = "UPDATE_ANNOUNCEMENT_FAIL";
export const UPDATE_ANNOUNCEMENT_RESET = "UPDATE_ANNOUNCEMENT_RESET";

export const DELETE_ANNOUNCEMENT_REQUEST = "DELETE_ANNOUNCEMENT_REQUEST";
export const DELETE_ANNOUNCEMENT_SUCCESS = "DELETE_ANNOUNCEMENT_SUCCESS";
export const DELETE_ANNOUNCEMENT_FAIL = "DELETE_ANNOUNCEMENT_FAIL";
export const DELETE_ANNOUNCEMENT_RESET = "DELETE_ANNOUNCEMENT_RESET";

export const USER_ANNOUNCEMENTS_REQUEST = "USER_ANNOUNCEMENTS_REQUEST";
export const USER_ANNOUNCEMENTS_SUCCESS = "USER_ANNOUNCEMENTS_SUCCESS";
export const USER_ANNOUNCEMENTS_FAIL = "USER_ANNOUNCEMENTS_FAIL";

export const SET_ANNOUNCEMENTS = "SET_ANNOUNCEMENTS"; // Add this line

export const CLEAR_ERRORS = "CLEAR_ERRORS";
