export const CREATE_APPOINTMENT_REQUEST = "CREATE_APPOINTMENT_REQUEST";
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";
export const CREATE_APPOINTMENT_FAIL = "CREATE_APPOINTMENT_FAIL";

export const MY_APPOINTMENTS_REQUEST = "MY_APPOINTMENTS_REQUEST";
export const MY_APPOINTMENTS_SUCCESS = "MY_APPOINTMENTS_SUCCESS";
export const MY_APPOINTMENTS_FAIL = "MY_APPOINTMENTS_FAIL";

export const NEW_APPOINTMENT_REQUEST = "NEW_APPOINTMENT_REQUEST";
export const NEW_APPOINTMENT_SUCCESS = "NEW_APPOINTMENT_SUCCESS";
export const NEW_APPOINTMENT_RESET = "NEW_APPOINTMENT_RESET";
export const NEW_APPOINTMENT_FAIL = "NEW_APPOINTMENT_FAIL";

export const APPOINTMENT_DETAILS_REQUEST = "APPOINTMENT_DETAILS_REQUEST";
export const APPOINTMENT_DETAILS_SUCCESS = "APPOINTMENT_DETAILS_SUCCESS";
export const APPOINTMENT_DETAILS_FAIL = "APPOINTMENT_DETAILS_FAIL";

export const ALL_APPOINTMENTS_REQUEST = "ALL_APPOINTMENTS_REQUEST";
export const ALL_APPOINTMENTS_SUCCESS = "ALL_APPOINTMENTS_SUCCESS";
export const ALL_APPOINTMENTS_FAIL = "ALL_APPOINTMENTS_FAIL";

export const UPDATE_APPOINTMENT_REQUEST = "UPDATE_APPOINTMENT_REQUEST";
export const UPDATE_APPOINTMENT_SUCCESS = "UPDATE_APPOINTMENT_SUCCESS";
export const UPDATE_APPOINTMENT_FAIL = "UPDATE_APPOINTMENT_FAIL";
export const UPDATE_APPOINTMENT_RESET = "UPDATE_APPOINTMENT_RESET";

export const DELETE_APPOINTMENT_REQUEST = "DELETE_APPOINTMENT_REQUEST";
export const DELETE_APPOINTMENT_SUCCESS = "DELETE_APPOINTMENT_SUCCESS";
export const DELETE_APPOINTMENT_FAIL = "DELETE_APPOINTMENT_FAIL";
export const DELETE_APPOINTMENT_RESET = "DELETE_APPOINTMENT_RESET";

export const USER_APPOINTMENTS_REQUEST = "USER_APPOINTMENTS_REQUEST";
export const USER_APPOINTMENTS_SUCCESS = "USER_APPOINTMENTS_SUCCESS";
export const USER_APPOINTMENTS_FAIL = "USER_APPOINTMENTS_FAIL";

// Add a new action type for joining an appointment
export const APPOINTMENT_JOIN_SUCCESS = 'APPOINTMENT_JOIN_SUCCESS';
export const APPOINTMENT_JOIN_FAIL = 'APPOINTMENT_JOIN_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";
