export const CREATE_BORROW_REQUEST = "CREATE_BORROW_REQUEST";
export const CREATE_BORROW_SUCCESS = "CREATE_BORROW_SUCCESS";
export const CREATE_BORROW_FAIL = "CREATE_BORROW_FAIL";
export const MY_BORROWS_REQUEST = "MY_BORROWS_REQUEST";

export const MY_BORROWS_SUCCESS = "MY_BORROWS_SUCCESS";

export const MY_BORROWS_FAIL = "MY_BORROWS_FAIL";
export const BORROW_DETAILS_REQUEST = "BORROW_DETAILS_REQUEST";

export const BORROW_DETAILS_SUCCESS = "BORROW_DETAILS_SUCCESS";

export const BORROW_DETAILS_FAIL = "BORROW_DETAILS_FAIL";
export const ALL_BORROWS_REQUEST = "ALL_BORROWS_REQUEST";

export const ALL_BORROWS_SUCCESS = "ALL_BORROWS_SUCCESS";

export const ALL_BORROWS_FAIL = "ALL_BORROWS_FAIL";
export const UPDATE_BORROW_REQUEST = "UPDATE_BORROW_REQUEST";

export const UPDATE_BORROW_SUCCESS = "UPDATE_BORROW_SUCCESS";

export const UPDATE_BORROW_RESET = "UPDATE_BORROW_RESET";

export const UPDATE_BORROW_FAIL = "UPDATE_BORROW_FAIL";
export const DELETE_BORROW_REQUEST = "DELETE_BORROW_REQUEST";

export const DELETE_BORROW_SUCCESS = "DELETE_BORROW_SUCCESS";

export const DELETE_BORROW_RESET = "DELETE_BORROW_RESET";

export const DELETE_BORROW_FAIL = "DELETE_BORROW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
