export const ADD_TO_BORROW_CART = "ADD_TO_BORROW_CART";
export const REMOVE_ITEM_BORROW_CART = "REMOVE_ITEM_BORROW_CART";
export const SAVE_BORROWING_INFO = "SAVE_BORROW_BORROWING_INFO";
export const CLEAR_BORROW_CART = "CLEAR_BORROW_CART";
