export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";

export const MY_CATEGORIES_REQUEST = "MY_CATEGORIES_REQUEST";
export const MY_CATEGORIES_SUCCESS = "MY_CATEGORIES_SUCCESS";
export const MY_CATEGORIES_FAIL = "MY_CATEGORIES_FAIL";

export const NEW_CATEGORY_REQUEST = "NEW_CATEGORY_REQUEST";
export const NEW_CATEGORY_SUCCESS = "NEW_CATEGORY_SUCCESS";
export const NEW_CATEGORY_RESET = "NEW_CATEGORY_RESET"; // Added reset action
export const NEW_CATEGORY_FAIL = "NEW_CATEGORY_FAIL";

export const CATEGORY_DETAILS_REQUEST = "CATEGORY_DETAILS_REQUEST";
export const CATEGORY_DETAILS_SUCCESS = "CATEGORY_DETAILS_SUCCESS";
export const CATEGORY_DETAILS_FAIL = "CATEGORY_DETAILS_FAIL";

export const ALL_CATEGORIES_REQUEST = "ALL_CATEGORIES_REQUEST";
export const ALL_CATEGORIES_SUCCESS = "ALL_CATEGORIES_SUCCESS";
export const ALL_CATEGORIES_FAIL = "ALL_CATEGORIES_FAIL";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";
export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET"; // Added reset action

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
export const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET"; // Added reset action

export const USER_CATEGORIES_REQUEST = "USER_CATEGORIES_REQUEST";
export const USER_CATEGORIES_SUCCESS = "USER_CATEGORIES_SUCCESS";
export const USER_CATEGORIES_FAIL = "USER_CATEGORIES_FAIL";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const DEACTIVATE_CATEGORY_REQUEST = "DEACTIVATE_CATEGORY_REQUEST"; // Added deactivate request constant
export const DEACTIVATE_CATEGORY_SUCCESS = "DEACTIVATE_CATEGORY_SUCCESS"; // Added deactivate success constant
export const DEACTIVATE_CATEGORY_FAIL = "DEACTIVATE_CATEGORY_FAIL"; // Added deactivate fail constant
export const DEACTIVATE_CATEGORY_RESET = "DEACTIVATE_CATEGORY_RESET"; // Added deactivate reset constant

export const REACTIVATE_CATEGORY_REQUEST = "REACTIVATE_CATEGORY_REQUEST"; // Added reactivate request constant
export const REACTIVATE_CATEGORY_SUCCESS = "REACTIVATE_CATEGORY_SUCCESS"; // Added reactivate success constant
export const REACTIVATE_CATEGORY_FAIL = "REACTIVATE_CATEGORY_FAIL"; // Added reactivate fail constant
export const REACTIVATE_CATEGORY_RESET = "REACTIVATE_CATEGORY_RESET"; // Added reactivate reset constant
