export const CREATE_EQUIPMENT_REQUEST = "CREATE_EQUIPMENT_REQUEST";
export const CREATE_EQUIPMENT_SUCCESS = "CREATE_EQUIPMENT_SUCCESS";
export const CREATE_EQUIPMENT_FAIL = "CREATE_EQUIPMENT_FAIL";

export const MY_EQUIPMENTS_REQUEST = "MY_EQUIPMENTS_REQUEST";
export const MY_EQUIPMENTS_SUCCESS = "MY_EQUIPMENTS_SUCCESS";
export const MY_EQUIPMENTS_FAIL = "MY_EQUIPMENTS_FAIL";

export const NEW_EQUIPMENT_REQUEST = "NEW_EQUIPMENT_REQUEST";
export const NEW_EQUIPMENT_SUCCESS = "NEW_EQUIPMENT_SUCCESS";
export const NEW_EQUIPMENT_RESET = "NEW_EQUIPMENT_RESET";
export const NEW_EQUIPMENT_FAIL = "NEW_EQUIPMENT_FAIL";

export const EQUIPMENT_DETAILS_REQUEST = "EQUIPMENT_DETAILS_REQUEST";
export const EQUIPMENT_DETAILS_SUCCESS = "EQUIPMENT_DETAILS_SUCCESS";
export const EQUIPMENT_DETAILS_FAIL = "EQUIPMENT_DETAILS_FAIL";

export const ALL_EQUIPMENTS_REQUEST = "ALL_EQUIPMENTS_REQUEST";
export const ALL_EQUIPMENTS_SUCCESS = "ALL_EQUIPMENTS_SUCCESS";
export const ALL_EQUIPMENTS_FAIL = "ALL_EQUIPMENTS_FAIL";

export const UPDATE_EQUIPMENT_REQUEST = "UPDATE_EQUIPMENT_REQUEST";
export const UPDATE_EQUIPMENT_SUCCESS = "UPDATE_EQUIPMENT_SUCCESS";
export const UPDATE_EQUIPMENT_FAIL = "UPDATE_EQUIPMENT_FAIL";
export const UPDATE_EQUIPMENT_RESET = "UPDATE_EQUIPMENT_RESET";

export const DELETE_EQUIPMENT_REQUEST = "DELETE_EQUIPMENT_REQUEST";
export const DELETE_EQUIPMENT_SUCCESS = "DELETE_EQUIPMENT_SUCCESS";
export const DELETE_EQUIPMENT_FAIL = "DELETE_EQUIPMENT_FAIL";
export const DELETE_EQUIPMENT_RESET = "DELETE_EQUIPMENT_RESET";

export const USER_EQUIPMENTS_REQUEST = "USER_EQUIPMENTS_REQUEST";
export const USER_EQUIPMENTS_SUCCESS = "USER_EQUIPMENTS_SUCCESS";
export const USER_EQUIPMENTS_FAIL = "USER_EQUIPMENTS_FAIL";

export const DEACTIVATE_EQUIPMENT_REQUEST = "DEACTIVATE_EQUIPMENT_REQUEST";
export const DEACTIVATE_EQUIPMENT_SUCCESS = "DEACTIVATE_EQUIPMENT_SUCCESS";
export const DEACTIVATE_EQUIPMENT_FAIL = "DEACTIVATE_EQUIPMENT_FAIL";
export const DEACTIVATE_EQUIPMENT_RESET = "DEACTIVATE_EQUIPMENT_RESET";

export const REACTIVATE_EQUIPMENT_REQUEST = "REACTIVATE_EQUIPMENT_REQUEST";
export const REACTIVATE_EQUIPMENT_SUCCESS = "REACTIVATE_EQUIPMENT_SUCCESS";
export const REACTIVATE_EQUIPMENT_FAIL = "REACTIVATE_EQUIPMENT_FAIL";
export const REACTIVATE_EQUIPMENT_RESET = "REACTIVATE_EQUIPMENT_RESET";

export const SET_EQUIPMENTS = "SET_EQUIPMENTS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
