export const CREATE_LOCATION_REQUEST = "CREATE_LOCATION_REQUEST";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_FAIL = "CREATE_LOCATION_FAIL";

export const MY_LOCATIONS_REQUEST = "MY_LOCATIONS_REQUEST";
export const MY_LOCATIONS_SUCCESS = "MY_LOCATIONS_SUCCESS";
export const MY_LOCATIONS_FAIL = "MY_LOCATIONS_FAIL";

export const NEW_LOCATION_REQUEST = "NEW_LOCATION_REQUEST";
export const NEW_LOCATION_SUCCESS = "NEW_LOCATION_SUCCESS";
export const NEW_LOCATION_RESET = "NEW_LOCATION_RESET";
export const NEW_LOCATION_FAIL = "NEW_LOCATION_FAIL";

export const LOCATION_DETAILS_REQUEST = "LOCATION_DETAILS_REQUEST";
export const LOCATION_DETAILS_SUCCESS = "LOCATION_DETAILS_SUCCESS";
export const LOCATION_DETAILS_FAIL = "LOCATION_DETAILS_FAIL";

export const ALL_LOCATIONS_REQUEST = "ALL_LOCATIONS_REQUEST";
export const ALL_LOCATIONS_SUCCESS = "ALL_LOCATIONS_SUCCESS";
export const ALL_LOCATIONS_FAIL = "ALL_LOCATIONS_FAIL";

export const UPDATE_LOCATION_REQUEST = "UPDATE_LOCATION_REQUEST";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAIL = "UPDATE_LOCATION_FAIL";
export const UPDATE_LOCATION_RESET = "UPDATE_LOCATION_RESET";

export const DELETE_LOCATION_REQUEST = "DELETE_LOCATION_REQUEST";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAIL = "DELETE_LOCATION_FAIL";
export const DELETE_LOCATION_RESET = "DELETE_LOCATION_RESET";

export const DEACTIVATE_LOCATION_REQUEST = "DEACTIVATE_LOCATION_REQUEST";
export const DEACTIVATE_LOCATION_SUCCESS = "DEACTIVATE_LOCATION_SUCCESS";
export const DEACTIVATE_LOCATION_FAIL = "DEACTIVATE_LOCATION_FAIL";
export const DEACTIVATE_LOCATION_RESET = "DEACTIVATE_LOCATION_RESET";

export const REACTIVATE_LOCATION_REQUEST = "REACTIVATE_LOCATION_REQUEST";
export const REACTIVATE_LOCATION_SUCCESS = "REACTIVATE_LOCATION_SUCCESS";
export const REACTIVATE_LOCATION_FAIL = "REACTIVATE_LOCATION_FAIL";
export const REACTIVATE_LOCATION_RESET = "REACTIVATE_LOCATION_RESET";

export const USER_LOCATIONS_REQUEST = "USER_LOCATIONS_REQUEST";
export const USER_LOCATIONS_SUCCESS = "USER_LOCATIONS_SUCCESS";
export const USER_LOCATIONS_FAIL = "USER_LOCATIONS_FAIL";

export const SET_LOCATIONS = "SET_LOCATIONS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
