export const CREATE_NOTIFICATION_REQUEST = "CREATE_NOTIFICATION_REQUEST";
export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS";
export const CREATE_NOTIFICATION_FAIL = "CREATE_NOTIFICATION_FAIL";

export const MY_NOTIFICATIONS_REQUEST = "MY_NOTIFICATIONS_REQUEST";
export const MY_NOTIFICATIONS_SUCCESS = "MY_NOTIFICATIONS_SUCCESS";
export const MY_NOTIFICATIONS_FAIL = "MY_NOTIFICATIONS_FAIL";

export const NEW_NOTIFICATION_REQUEST = "NEW_NOTIFICATION_REQUEST";
export const NEW_NOTIFICATION_SUCCESS = "NEW_NOTIFICATION_SUCCESS";
export const NEW_NOTIFICATION_RESET = "NEW_NOTIFICATION_RESET";
export const NEW_NOTIFICATION_FAIL = "NEW_NOTIFICATION_FAIL";

export const NOTIFICATION_DETAILS_REQUEST = "NOTIFICATION_DETAILS_REQUEST";
export const NOTIFICATION_DETAILS_SUCCESS = "NOTIFICATION_DETAILS_SUCCESS";
export const NOTIFICATION_DETAILS_FAIL = "NOTIFICATION_DETAILS_FAIL";

export const ALL_NOTIFICATIONS_REQUEST = "ALL_NOTIFICATIONS_REQUEST";
export const ALL_NOTIFICATIONS_SUCCESS = "ALL_NOTIFICATIONS_SUCCESS";
export const ALL_NOTIFICATIONS_FAIL = "ALL_NOTIFICATIONS_FAIL";

export const UPDATE_NOTIFICATION_REQUEST = "UPDATE_NOTIFICATION_REQUEST";
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";
export const UPDATE_NOTIFICATION_FAIL = "UPDATE_NOTIFICATION_FAIL";
export const UPDATE_NOTIFICATION_RESET = "UPDATE_NOTIFICATION_RESET";

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAIL = "DELETE_NOTIFICATION_FAIL";
export const DELETE_NOTIFICATION_RESET = "DELETE_NOTIFICATION_RESET";

export const USER_NOTIFICATIONS_REQUEST = "USER_NOTIFICATIONS_REQUEST";
export const USER_NOTIFICATIONS_SUCCESS = "USER_NOTIFICATIONS_SUCCESS";
export const USER_NOTIFICATIONS_FAIL = "USER_NOTIFICATIONS_FAIL";

export const DEACTIVATE_NOTIFICATION_REQUEST =
  "DEACTIVATE_NOTIFICATION_REQUEST";
export const DEACTIVATE_NOTIFICATION_SUCCESS =
  "DEACTIVATE_NOTIFICATION_SUCCESS";
export const DEACTIVATE_NOTIFICATION_FAIL = "DEACTIVATE_NOTIFICATION_FAIL";
export const DEACTIVATE_NOTIFICATION_RESET = "DEACTIVATE_NOTIFICATION_RESET";

export const REACTIVATE_NOTIFICATION_REQUEST =
  "REACTIVATE_NOTIFICATION_REQUEST";
export const REACTIVATE_NOTIFICATION_SUCCESS =
  "REACTIVATE_NOTIFICATION_SUCCESS";
export const REACTIVATE_NOTIFICATION_FAIL = "REACTIVATE_NOTIFICATION_FAIL";
export const REACTIVATE_NOTIFICATION_RESET = "REACTIVATE_NOTIFICATION_RESET";

export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
