export const CREATE_SPORT_REQUEST = "CREATE_SPORT_REQUEST";
export const CREATE_SPORT_SUCCESS = "CREATE_SPORT_SUCCESS";
export const CREATE_SPORT_FAIL = "CREATE_SPORT_FAIL";

export const MY_SPORTS_REQUEST = "MY_SPORTS_REQUEST";
export const MY_SPORTS_SUCCESS = "MY_SPORTS_SUCCESS";
export const MY_SPORTS_FAIL = "MY_SPORTS_FAIL";

export const NEW_SPORT_REQUEST = "NEW_SPORT_REQUEST";
export const NEW_SPORT_SUCCESS = "NEW_SPORT_SUCCESS";
export const NEW_SPORT_RESET = "NEW_SPORT_RESET";
export const NEW_SPORT_FAIL = "NEW_SPORT_FAIL";

export const SPORT_DETAILS_REQUEST = "SPORT_DETAILS_REQUEST";
export const SPORT_DETAILS_SUCCESS = "SPORT_DETAILS_SUCCESS";
export const SPORT_DETAILS_FAIL = "SPORT_DETAILS_FAIL";

export const ALL_SPORTS_REQUEST = "ALL_SPORTS_REQUEST";
export const ALL_SPORTS_SUCCESS = "ALL_SPORTS_SUCCESS";
export const ALL_SPORTS_FAIL = "ALL_SPORTS_FAIL";

export const UPDATE_SPORT_REQUEST = "UPDATE_SPORT_REQUEST";
export const UPDATE_SPORT_SUCCESS = "UPDATE_SPORT_SUCCESS";
export const UPDATE_SPORT_FAIL = "UPDATE_SPORT_FAIL";
export const UPDATE_SPORT_RESET = "UPDATE_SPORT_RESET";

export const DELETE_SPORT_REQUEST = "DELETE_SPORT_REQUEST";
export const DELETE_SPORT_SUCCESS = "DELETE_SPORT_SUCCESS";
export const DELETE_SPORT_FAIL = "DELETE_SPORT_FAIL";
export const DELETE_SPORT_RESET = "DELETE_SPORT_RESET";

export const USER_SPORTS_REQUEST = "USER_SPORTS_REQUEST";
export const USER_SPORTS_SUCCESS = "USER_SPORTS_SUCCESS";
export const USER_SPORTS_FAIL = "USER_SPORTS_FAIL";

export const DEACTIVATE_SPORT_REQUEST = "DEACTIVATE_SPORT_REQUEST";
export const DEACTIVATE_SPORT_SUCCESS = "DEACTIVATE_SPORT_SUCCESS";
export const DEACTIVATE_SPORT_FAIL = "DEACTIVATE_SPORT_FAIL";
export const DEACTIVATE_SPORT_RESET = "DEACTIVATE_SPORT_RESET";

export const REACTIVATE_SPORT_REQUEST = "REACTIVATE_SPORT_REQUEST";
export const REACTIVATE_SPORT_SUCCESS = "REACTIVATE_SPORT_SUCCESS";
export const REACTIVATE_SPORT_FAIL = "REACTIVATE_SPORT_FAIL";
export const REACTIVATE_SPORT_RESET = "REACTIVATE_SPORT_RESET";

export const SET_SPORTS = "SET_SPORTS"; // Added this line

export const CLEAR_ERRORS = "CLEAR_ERRORS";
